package com.vgtech.mobile.data.model

import java.util.UUID

enum class TransactionType {
    SERVICE, // When a client pays for a service (adds debt/revenue)
    PAYMENT  // When the company pays the provider (reduces debt)
}

data class ProviderTransaction(
    val id: String = UUID.randomUUID().toString(),
    val providerId: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val type: TransactionType = TransactionType.SERVICE,
    
    // For SERVICE: Total client's payment
    // For PAYMENT: Amount paid to provider
    val rawAmount: Double = 0.0, 
    
    // Calculated values for SERVICE (e.g. 50/50 split)
    val companyCut: Double = 0.0,
    val providerCut: Double = 0.0,
    
    val description: String = ""
)

data class ProviderAccountSummary(
    val providerId: String,
    val providerName: String,
    // Total money generated by the provider (sum of providerCut from services)
    val totalServiceAmountEarned: Double,
    // Total money paid directly to the provider (sum of PAYMENT amounts)
    val totalAmountPaid: Double,
    // Remaining debt
    val pendingBalance: Double,
    // Company's total profit from this provider's services
    val totalCompanyProfit: Double
)
